name: ptcmil
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.2=hb9d3cd8_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py38h5eee18b_0
  - pip=24.0=py38h06a4308_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - psutil=6.0.0=py38hfb59056_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cpu
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py38hfb59056_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=ha4adb4c_5
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - addict==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.15.1
      - aliyun-python-sdk-kms==2.16.3
      - astor==0.8.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==42.0.7
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.0
      - filelock==3.14.0
      - fonttools==4.51.0
      - formulaic==1.0.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - graphlib-backport==1.1.0
      - h5py==3.11.0
      - huggingface-hub==0.26.2
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - install==1.3.5
      - interface-meta==1.3.0
      - iopath==0.1.10
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lifelines==0.27.8
      - lightning-utilities==0.11.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmcv-full==1.7.2
      - mmengine==0.10.4
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.1
      - numexpr==2.8.6
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - nystrom-attention==0.0.12
      - opencv-python==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openslide-python==1.3.1
      - openxlab==0.0.38
      - ordered-set==4.1.0
      - osqp==0.6.7.post0
      - oss2==2.17.0
      - packaging==24.0
      - pandas==2.0.3
      - platformdirs==4.2.2
      - portalocker==3.0.0
      - pot==0.9.4
      - protobuf==5.26.1
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.0
      - pytz==2023.4
      - pyyaml==6.0.1
      - qdldl==0.1.7.post4
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.4.3
      - scikit-learn==1.3.2
      - scikit-survival==0.22.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.18.0
      - setproctitle==1.3.4
      - setuptools==60.2.0
      - smmap==5.0.1
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - timm==0.9.8
      - tokenizers==0.20.3
      - tomli==2.0.1
      - torch==2.4.0
      - torchaudio==0.13.1
      - torchmetrics==1.4.0.post0
      - torchvision==0.14.1
      - tqdm==4.65.2
      - transformers==4.46.3
      - triton==3.0.0
      - tzdata==2024.1
      - urllib3==1.26.18
      - wandb==0.18.7
      - wrapt==1.16.0
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.18.1
prefix: ./
